- name: default
  servers:
  - name: sequential-thinking
    no_confirm: true
  - name: context7
    no_confirm: true
  - name: markitdowm
    no_confirm: true
  - name: brave-search
    no_confirm: false
- name: all
  servers:
  - name: sequential-thinking
    no_confirm: true
  - name: context7
    no_confirm: true
  - name: markitdowm
    no_confirm: true
  - name: brave-search
    no_confirm: false
  - name: mcp-atlassian
    no_confirm: false
  - name: github
    no_confirm: false
  - name: awslabs.core-mcp-server
    no_confirm: false
  - name: awslabs.core-mcp-server
    no_confirm: false
  - name: awslabs.terraform-mcp-server
    no_confirm: false
  - name: awslabs.aws-documentation-mcp-server
    no_confirm: false
