# test locally: $ act --secret-file .secrets
name: Build and push docker image
on:
  push:
    branches:
      - main
      - master
jobs:
  build_job:
    name: Job to build docker image of development environment on Ubuntu
    runs-on: ubuntu-18.04
    environment:
      name: prod
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: docker/ubuntu/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dotfiles:ubuntu
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
